In [1]:
import numpy as np
import tt
import cross

In [2]:
n_objects = 10
n_features = 5

np.random.seed(12311)

matrix = np.random.rand(n_objects, n_features)
def f(x):
    return matrix[np.array(x[:, 0]).astype(int), np.array(x[:, 1]).astype(int)]
x0 = tt.rand(np.array([n_objects, n_features]))
appr, c = cross.rect_cross(f, x0, eps=1e-1)

c = <cross.rectcross.rect_cross.tt_as_tree instance at 0x107f2a170>
swp: 0/9 er_rel = 1.8e+00 er_abs = 7.8e+00 erank = 5.0 fun_eval: 110
swp: 1/9 er_rel = 3.9e-16 er_abs = 1.7e-15 erank = 5.0 fun_eval: 280


In [3]:
U, V = tt.tensor.to_list(appr)
U = np.reshape(U, (n_objects, -1))
V = np.reshape(V, (-1, n_features))
np.linalg.norm(matrix - U.dot(V)) / np.linalg.norm(matrix)

0.26884112137751143

In [4]:
print U.shape
print V.shape
print "c.d =", c.d

for node in c.nodes:
    print "core: ", node.core
    for edge in node.edges:
        print "______________________"
        print "ind_left:\n", edge.ind_left, "\n"
        print "ind_right:\n", edge.ind_right, "\n"

(10, 5)
(5, 5)
c.d = 2
core:  [[[ 0.80801337  0.68196812  0.93473676  0.71093448  0.43093641]
  [ 0.3756882   0.10352622  0.09778394  0.08499976  0.97707096]
  [ 0.19609705  0.85776473  0.95815499  0.19799744  0.85076136]
  [ 0.46640267  0.74177757  0.02175077  0.81157669  0.23294072]
  [ 0.88217521  0.43499265  0.65189397  0.32324087  0.75234721]
  [ 1.10086357  0.01202627  0.22425028  0.54393827  0.03847676]
  [ 0.20558081  0.85486469  0.94425239  0.44559461  0.86403808]
  [ 0.21098111  0.37786512  0.37037598  0.5874963   0.07997381]
  [ 1.06982277  0.04855144  0.81287823  0.52573     0.56210551]
  [ 0.41533016  0.95405802  0.36296657  0.47987442  0.54121384]]]
______________________
ind_left:
[] 

ind_right:
[[1 4]
 [6 1]
 [2 4]] 

______________________
ind_left:
[[6]
 [5]
 [1]
 [3]
 [7]
 [8]
 [9]] 

ind_right:
[[0]
 [1]
 [2]
 [3]
 [4]] 

core:  [[[ 1.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 1.]
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 1.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 